#!/usr/bin/env bash
#Redirection
#!/usr/bin/env bash
#Redirection
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start


echo "Hello World!" | sudo tee /var/www/html/index.html


otherdefault="/etc/nginx/sites-enabled/default"
location="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=ZZ5LpwO-An4;\n\t}\n"
sudo sed -i "30i $location" "$otherdefault"
sudo service nginx restart
